version: "3.9"
services:
  audiolevel:
    container_name: audiolevel
    privileged: true #this may not be necessary
    restart: unless-stopped
    shm_size: "256mb"
    image: audiolevel-docker:latest
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/user/foldername/config:/config/:ro


